server.port=8080

app.security.enabled=true

# Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.with-credentials=true
springdoc.swagger-ui.csrf.enabled=true

# Security
logging.level.org.springframework.security=TRACE

spring.jpa.open-in-view=false