# Spring Security default user (dev only)
api.username=dev
api.password=dev
spring.security.user.name=${api.username}
spring.security.user.password=${api.password}
logging.level.org.springframework.security=TRACE;

# CORS
cors.allowed-origins=http://localhost:5173,http://localhost:5174,http://localhost:3000,http://localhost:63342,http://127.0.0.1:63342,http://192.168.0.51:5173,http://192.168.0.51:5174

# H2
spring.datasource.url=jdbc:h2:file:./data/barbudb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=pwd
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console